### ISSUE TITLE
OWR: Chaos AI using Rites causing massive corruption + Empire Complaints

### ISSUE THREAD

**Issue by DrunkFlamingo** [WH2-WEC/wec#6]
@chadvandy I need a list of factions that shouldn't be able to use these rites when AI, and a list of the rites. By Subculture obviously.

I think its just the Stank rite and the Chaos Corruption rite.

**Comment by chadvandy** [comment]
wh_main_ritual_chs_storms - unusable by:

wh_dlc08_chs_chaos_challenger_khorne
wh_dlc08_chs_chaos_challenger_nurgle
wh_dlc08_chs_chaos_challenger_slaanesh
wh_dlc08_chs_chaos_challenger_tzeentch
wh_main_chs_chaos_rebels
wh2_main_chs_chaos_incursion_def
wh2_main_chs_chaos_incursion_hef
wh2_main_chs_chaos_incursion_lzd
wh2_main_chs_chaos_incursion_skv



Unusable until turn 25:
wh_main_ritual_emp_gunpowder
wh_main_ritual_grn_spidergod

**Comment by chadvandy** [comment]
Published the fixes, 06/24/18
